 SungeroElasticSearch:
        port: 9200
        # Port for the node-to-node interaction.
        port_tcp: 9300
        # Elasticsearch docker tag. If the parameter is not set, the default value is 'registry.directum.ru/public/elasticsearch:7.17.23'.
        docker_tag: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.23'
        es_data_path: '{{ home_path }}/elasticsearch/data'
        # Path to the synonyms file. If the file does not exist or the path is not specified, the file will be generated automatically.
        synonyms_file_path: '{{ home_path }}/elasticsearch/synonyms.txt'
        environments:
            # Elasticsearch node name used to identify a node in the cluster.
            ES_SETTING_NODE_NAME: 'es01'
            # Cluster name used to identify the cluster. The name must be the same for all nodes in the cluster.
            ES_SETTING_CLUSTER_NAME: 'es_cluster'
            # List of Elasticsearch nodes that can become master nodes when the cluster is first started.
            ES_SETTING_CLUSTER_INITIAL__MASTER__NODES: 'es01'
    SungeroKibana:
        port: 5601
        # Kibana docker tag. If the parameter is not set, the default value is 'registry.directum.ru/public/kibana:7.17.23'.
        docker_tag: 'docker.elastic.co/kibana/kibana:7.17.23'
        kibana_data_path: '{{ home_path }}/kibana/data'
        environments:
            # Public URL of Kibana.
            SERVER_PUBLICBASEURL: 'http://{{ host_fqdn }}:5601'
            # A list of Elasticsearch node addresses that Kibana will connect to.
            ELASTICSEARCH_HOSTS:
            -   'http://{{ host_fqdn }}:9200'

sudo chown -R 1000:0 /opt/monitoring/dir-data
sudo chmod -R g+rwx /opt/monitoring/dir-data
