1. Отключение SELinux и firewalld

setenforce 0
sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
grubby --update-kernel ALL --args selinux=0
systemctl disable --now firewalld
systemctl mask firewalld

2. Установка nfs-utils в обход битого зеркала

mkdir -p /tmp/nfs-rpm && cd /tmp/nfs-rpm
dnf download --resolve --alldeps --exclude=sssd-nfs-idmap nfs-utils
rpm -Uvh --nodeps *.rpm
rpm -Uvh --nodeps /tmp/nfs-rpm/nfs-utils*.rpm
rpm -Uvh --nodeps /tmp/nfs-rpm/rpcbind*.rpm
grep -q '^exclude=' /etc/dnf/dnf.conf || echo 'exclude=sssd-nfs-idmap' >> /etc/dnf/dnf.conf
cd ~

3. Каталог для данных

mkdir -p /srv/es-data
chown 1000:1000 /srv/es-data
chmod 0775 /srv/es-data

4. Публикация по NFS

grep -q '/srv/es-data' /etc/exports || echo '/srv/es-data 192.168.48.0/24(rw,sync,no_subtree_check,no_root_squash)' >> /etc/exports
systemctl daemon-reload
systemctl enable --now rpcbind nfs-server
exportfs -rav

5. Проверка

rpm -q nfs-utils rpcbind
systemctl is-active nfs-server
exportfs -v
ss -tlnp | grep 2049
showmount -e localhost
ls -ld /srv/es-data

6. Перезагрузка
reboot
getenforce
systemctl is-active nfs-server

Подключение папки на сервере Elasticsearch (замените IP на адрес nassan):

dnf -y install --setopt=install_weak_deps=False nfs-utils - если ошибка установки то:
# -------
mkdir -p /tmp/nfs-rpm && cd /tmp/nfs-rpm
dnf download --resolve --alldeps --exclude=sssd-nfs-idmap nfs-utils
rpm -Uvh --nodeps *.rpm
rpm -Uvh --nodeps /tmp/nfs-rpm/nfs-utils*.rpm
rpm -Uvh --nodeps /tmp/nfs-rpm/rpcbind*.rpm
grep -q '^exclude=' /etc/dnf/dnf.conf || echo 'exclude=sssd-nfs-idmap' >> /etc/dnf/dnf.conf
cd ~

rpm -q nfs-utils
which mount.nfs4
------

mkdir -p /mnt/es-data
echo '192.168.48.XX:/srv/es-data /mnt/es-data nfs4 defaults,_netdev,hard,timeo=600,retrans=2 0 0' >> /etc/fstab
mount -a
df -h /mnt/es-data
touch /mnt/es-data/test.txt && ls -l /mnt/es-data/ && rm /mnt/es-data/test.txt
